name: Provision EC2 and Deploy Website

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      ec2_ip: ${{ steps.tf.outputs.ec2_ip }}
      ec2_key: ${{ steps.tf.outputs.ec2_key }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraformEC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraformEC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Get Terraform Outputs
        id: tf
        working-directory: terraformEC2
        run: |
          echo "ec2_ip=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT
          echo "ec2_key<<EOF" >> $GITHUB_OUTPUT
          terraform output -raw ec2_private_key >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  deploy:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-website:latest

      - name: Wait for EC2 to be ready
        run: sleep 20

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ needs.terraform.outputs.ec2_ip }}
          username: ubuntu
          key: ${{ needs.terraform.outputs.ec2_key }}
          script: |
            until command -v docker >/dev/null 2>&1; do
              echo "Waiting for Docker to be installed..."
              sleep 30
            done
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-website:latest
            sudo docker stop website || true
            sudo docker rm website || true
            sudo docker run -d --name website -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-website:latest
